package com.iyr.ian

import android.content.Context
import com.iyr.ian.app.AppClass

class AppConstants(val context: Context) {


    companion object {
        const val MINIMUM_TAPS = 3
        const val MINIMUM_TOUCH_TIME = 3

        const val NEW_CONTACT_LIST_KEY = "new_contact_list"


        const val SLIDE_FRAGMENT_SHOW_SPEED: Long = 500
        const val SLIDE_FRAGMENT_HIDE_SPEED: Long = 300

        const val DYNAMIC_LINK_ACTION_FRIENDSHIP = "FRIENDSHIP"
        const val DYNAMIC_LINK_ACTION_FRIENDSHIP_AND_SPEED_DIAL = "FRIENDSHIP_AND_SPEED_DIAL"

        val DYNAMICLINKS_URI_PREFIX = "https://"
        var SERVER_LOCATION_UPDATES_INTERVAL = (1000 * 60).toLong()
        const val MESSENGER_INTENT_KEY = "msg-intent-key"
        const val USER_AGENT = "InstantAlertNetwork / 1.0.0"


        const val PERMISSIONS_REQUEST_READ_CONTACTS = 100

        const val NOTIFICATION_TYPE_PANIC_BUTTON = "NOTIFICATION_TYPE_PANIC_BUTTON"
        const val NOTIFICATION_ACTION_OPEN_CHAT = "NOTIFICATION_ACTION_OPEN_CHAT"
        const val NOTIFICATION_TYPE_NEW_MESSAGE = "NOTIFICATION_TYPE_MESSAGE"
        const val NOTIFICATION_TYPE_PULSE_REQUESTED = "NOTIFICATION_TYPE_PULSE_REQUESTED"
        const val NOTIFICATION_TYPE_ARE_YOU_ON_DESTINATION_REQUESTED =
            "NOTIFICATION_TYPE_ARE_YOU_ON_DESTINATION_REQUESTED"
        const val BROADCAST_BLOCKED_LAYOUT_REQUIRED = "BROADCAST_BLOCKED_LAYOUT_REQUIRED"
        const val BROADCAST_BLOCKED_LAYOUT_DISMISS = "BROADCAST_BLOCKED_LAYOUT_DISMISS"
        const val BROADCAST_PULSE_REQUIRED = "BROADCAST_PULSE_REQUIRED"
        const val BROADCAST_DID_YOU_ARRIVE_REQUEST = "BROADCAST_DID_YOU_ARRIVE_REQUEST"
        const val BROADCAST_EVENT_CLOSE_TO_EXPIRE = "BROADCAST_EVENT_CLOSE_TO_EXPIRE"
        const val BROADCAST_UNREAD_MESSAGES_UPDATES = "BROADCAST_UNREAD_MESSAGES_UPDATES"
        const val BROADCAST_ACTION_REFRESH_PANIC_BUTTON = "BROADCAST_ACTION_REFRESH_PANIC_BUTTON"
        const val BROADCAST_ACTION_SHOW_FOOTER_TOOLBAR = "BROADCAST_ACTION_SHOW_FOOTER_TOOLBAR"
        const val BROADCAST_ACTION_HIDE_FOOTER_TOOLBAR = "BROADCAST_ACTION_HIDE_FOOTER_TOOLBAR"
        const val BROADCAST_ACTION_CANCEL_PANIC = "BROADCAST_ACTION_CANCEL_PANIC"
        const val BROADCAST_ACTION_REQUEST_PIN =
            "BROADCAST_ACTION_REQUEST_PIN" // Ordena que se muestre el cuadro de PIN
        const val BROADCAST_EVENT_FOLLOWED_ADDED = "BROADCAST_EVENT_FOLLOWED_ADDED"
        const val BROADCAST_EVENT_FOLLOWED_UPDATED = "BROADCAST_EVENT_FOLLOWED_UPDATED"
        const val BROADCAST_EVENT_FOLLOWED_REMOVED = "BROADCAST_EVENT_FOLLOWED_REMOVED"

        const val BROADCAST_ACTION_ENTER_FOREGROUND = "ACTION_ENTER_FOREGROUND"
        const val BROADCAST_ACTION_ENTER_BACKGROUND = "ACTION_ENTER_BACKGROUND"


        const val PASSWORD_MINIMUM_LENGTH = 8
        const val USERNAME_MINIMUM_LENGTH = 8
        const val FIRSTNAME_MINIMUM_LENGTH = 3
        const val LASTNAME_MINIMUM_LENGTH = 3
        const val COUNTDOWN_TIMER_SECONDS = 5
        const val PULSE_VALIDATOR_RETRY_COUNT = 3


        //-- MAPS
        const val ZOOM_TO_COUNTRY: Float = 4f
        const val ZOOM_TO_STATE: Float = 10f
        const val ZOOM_TO_CITY: Float = 12f
        const val ZOOM_TO_NEIGHBORGHOOD = 14f
        const val ZOOM_TO_SHOW_A_PLACE = 16f
        const val ZOOM_TO_STREETS = 18f

        //-- STORAGE
        const val PROFILE_IMAGES_STORAGE_PATH: String = "images/users/profiles/"
        const val CHAT_FILES_STORAGE_PATH = "chats/"

        //-- NOTIFICATION CHANNELS -->
        val CHANNEL_DEFAULT_ID = "IAN_NOTIFICATIONS"
        const val CHANNEL_DEFAULT_NAME = "IAN_NOTIFICATIONS_DEFAULT"
        const val CHANNEL_DEFAULT_DESCRIPTION = "Notificaciones Generales"
        const val CHANNEL_ALARM_ID = "IAN_NOTIFICATIONS_ALARMS"
        const val CHANNEL_ALARM_NAME = "IAN_NOTIFICATIONS_ALARMS"
        const val CHANNEL_ALARM_DESCRIPTION = "Notificaciones de Alarmas"



        const val BACKGROUND_STATE_NOTIFICATION_ID = 1
        const val BACKGROUND_STATE_CHANNEL_ID = "IAN_NOTIFICATIONS_BACKGROUND_STATE"
        const val BACKGROUND_STATE_CHANNEL_NAME = "IAN_NOTIFICATIONS_BACKGROUND_STATE"
        const val BACKGROUND_STATE_CHANNEL_DESCRIPTION = "Notificacion de estado de la aplicacion"





    }

    object ServiceCode {
        const val SERVICE_CODE_LOGIN = 1
        const val SERVICE_CODE_SIGNUP = 2
        const val SERVICE_CODE_FORGOT_PASSWORD = 3
        const val BROADCAST_ACTION_SHOW_FOOTER_TOOLBAR = "BROADCAST_ACTION_SHOW_FOOTER_TOOLBAR"
        const val BROADCAST_ACTION_HIDE_FOOTER_TOOLBAR = "BROADCAST_ACTION_HIDE_FOOTER_TOOLBAR"
        const val BROADCAST_PERMISSION_SEND_SMS_GRANTED = "BROADCAST_PERMISSION_SEND_SMS_GRANTED"
        const val BROADCAST_PERMISSION_SEND_SMS_DENIED = "BROADCAST_PERMISSION_SEND_SMS_DENIED"
        const val BROADCAST_MESSAGE_UPDATE_BLE_DEVICES_INDICATOR_REQUESTED =
            "BROADCAST_MESSAGE_UPDATE_BLE_DEVICES_REQUESTED"
        const val BROADCAST_MESSAGE_REFRESH_BLE_DEVICES_LIST =
            "BROADCAST_MESSAGE_REFRESh_BLE_DEVICES_LIST"
        const val BROADCAST_ACTION_REFRESH_PANIC_BUTTON = "BROADCAST_ACTION_REFRESH_PANIC_BUTTON"
        const val BROADCAST_ACTION_CANCEL_PANIC = "BROADCAST_ACTION_CANCEL_PANIC"
        const val BROADCAST_AFTER_EVENT_CLOSE = "BROADCAST_AFTER_EVENT_CLOSE"
        const val BROADCAST_EVENT_CLOSE_EVENT = "BROADCAST_EVENT_CLOSE_EVENT"
        const val BROADCAST_ACTION_REQUEST_PIN =
            "BROADCAST_ACTION_REQUEST_PIN" // Ordena que se muestre el cuadro de PIN
        const val REQUEST_PIN_FOR_CANCEL_EVENT = "REQUEST_PIN_FOR_CANCEL_EVENT"
        const val BROADCAST_ACTION_GO_TO_MAIN_ACTIVITY = "BROADCAST_ACTION_GO_TO_MAIN_ACTIVITY"

        const val MINIMUM_TAPS = 3
        const val MINIMUM_TOUCH_TIME = 3
        const val BROADCAST_MESSAGE_PANIC_BUTTON_PRESSED = "BROADCAST_MESSAGE_PANIC_BUTTON_PRESSED"
        var DYNAMICLINKS_PAGE_LINK: String = AppClass.instance.getString(R.string.dynamic_links_page)
    }

    init {

    }

}

