package com.iyr.ian.utils.bluetooth.constants

class BTConstants {

    companion object {
        const val MY_PERMISSIONS_REQUEST_BLUETOOTH_PERMISSIONS = 7002

        val BROADCAST_MESSAGE_BLE_SERVICE_CONNECTED = "BROADCAST_MESSAGE_BLE_SERVICE_CONNECTED"
        val BROADCAST_MESSAGE_BLE_SERVICE_DISCONNECTED = "BROADCAST_MESSAGE_BLE_SERVICE_DISCONNECTED"
        val BROADCAST_MESSAGE_BLE_DEVICE_DISCONNECTED = "BROADCAST_MESSAGE_BLE_DEVICE_DISCONNECTED"
        val BROADCAST_MESSAGE_BLE_DEVICE_CONNECTED = "BROADCAST_MESSAGE_BLE_DEVICE_CONNECTED"
        val BROADCAST_ACTION_BLE_DEVICE_ADD_TO_AUTO_CONNECTION =
            "BROADCAST_ACTION_BLE_DEVICE_ADD_TO_AUTO_CONNECTION"
        val BROADCAST_ACTION_BLE_DEVICE_REMOVE_FROM_AUTO_CONNECTION =
            "BROADCAST_ACTION_BLE_DEVICE_REMOVE_FROM_AUTO_CONNECTION"
        val BROADCAST_MESSAGE_BLE_REFRESH_DEVICES_LIST = "BROADCAST_MESSAGE_BLE_REFRESH_DEVICES_LIST"
        val BROADCAST_MESSAGE_BLE_REFRESH_DEVICES_DISCONNECTED =
            "BROADCAST_MESSAGE_BLE_REFRESH_DEVICES_DISCONNECTED"
        val BROADCAST_MESSAGE_BLE_DEVICE_DISCOVERED = "BROADCAST_MESSAGE_BLE_DEVICE_DISCOVERED"
        val BROADCAST_MESSAGE_BLE_DEVICE_UPDATED = "BROADCAST_MESSAGE_BLE_DEVICE_UPDATED"
        val BROADCAST_MESSAGE_BLE_DEVICE_FOUND = "BROADCAST_MESSAGE_BLE_DEVICE_FOUND"
        val BROADCAST_MESSAGE_PANIC_BUTTON_TEST = "BROADCAST_MESSAGE_PANIC_BUTTON_TEST"
        val BROADCAST_MESSAGE_DEVICE_TURNED_OFF = "BROADCAST_MESSAGE_DEVICE_TURNED_OFF"
        val BROADCAST_MESSAGE_REFRESH_BLE_DEVICES_LIST = "BROADCAST_MESSAGE_REFRESH_BLE_DEVICES_LIST"

        // public static final String BROADCAST_PANIC_BUTTON_PRESSED = "BROADCAST_PANIC_BUTTON_PRESSED";
        const val BROADCAST_MESSAGE_SCAN_RESULT_UPDATED = "BROADCAST_MESSAGE_SCAN_RESULT_UPDATED"


    }

}